[package]
name = "petit-js"
description = "Minimal embeddable JavaScript subset"
version = "0.1.0"
authors = ["Lucas Pickering <lucas@lucaspickering.me>"]
repository = "https://github.com/LucasPickering/petit-js"
edition = "2021"
license = "MIT"
# Keep in sync w/ rust-toolchain.toml# TODO downgrade MSRV
rust-version = "1.80.0"

[dependencies]

[workspace.metadata.release]
pre-release-replacements = [
    { file = "CHANGELOG.md", search = "## \\[Unreleased\\] - ReleaseDate", replace = "## [Unreleased] - ReleaseDate\n\n## [] - " },
]
