[package]
authors = ["Lucas Pickering <lucas@lucaspickering.me>"]
description = "Minimal embeddable JavaScript subset"
edition = "2021"
license = "MIT"
name = "petit-js"
repository = "https://github.com/LucasPickering/petit-js"
version = "0.1.0"
# Keep in sync w/ rust-toolchain.toml
rust-version = "1.82.0"

[[bin]]
name = "petit_js"
path = "src/main.rs"

[dependencies]
boa_ast = {path = "../boa/core/ast", default-features = false}
boa_interner = {path = "../boa/core/interner", default-features = false}
boa_parser = {path = "../boa/core/parser", default-features = false}
indexmap = {version = "2.7.0", features = ["serde"]}
thiserror = "2.0.10"
winnow = "0.6.21"

[workspace.metadata.release]
pre-release-replacements = [
  {file = "CHANGELOG.md", search = "## \\[Unreleased\\] - ReleaseDate", replace = "## [Unreleased] - ReleaseDate\n\n## [] - "},
]
