[package]
authors = ["Lucas Pickering <lucas@lucaspickering.me>"]
description = "Minimal embeddable JavaScript subset"
edition = "2021"
license = "MIT"
name = "petit-js"
repository = "https://github.com/LucasPickering/petit-js"
version = "0.1.0"
# Keep in sync w/ rust-toolchain.toml
# TODO downgrade MSRV
rust-version = "1.80.0"

[dependencies]
indexmap = {version = "2.7.0", features = ["serde"]}
winnow = "0.6.21"

[workspace.metadata.release]
pre-release-replacements = [
  {file = "CHANGELOG.md", search = "## \\[Unreleased\\] - ReleaseDate", replace = "## [Unreleased] - ReleaseDate\n\n## [] - "},
]
